// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { Prompt } from "./prompt_type";
// Mark import as potentially unused
declare type __keep_Prompt = Prompt;
import { Player } from "./player_type";
// Mark import as potentially unused
declare type __keep_Player = Player;
import { Vote } from "./vote_type";
// Mark import as potentially unused
declare type __keep_Vote = Vote;


export type GameState = {
  game: string,
  state: string,
  currentFocus: string,
  previousTraitor: string,
  prompt: Prompt | undefined,
  players: Player[],
  votes: Vote[],
};
/**
 * An object for generated helper functions.
 */
export const GameState = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "game", algebraicType: __AlgebraicTypeValue.String},
        { name: "state", algebraicType: __AlgebraicTypeValue.String},
        { name: "currentFocus", algebraicType: __AlgebraicTypeValue.String},
        { name: "previousTraitor", algebraicType: __AlgebraicTypeValue.String},
        { name: "prompt", algebraicType: __AlgebraicTypeValue.createOptionType(Prompt.getTypeScriptAlgebraicType())},
        { name: "players", algebraicType: __AlgebraicTypeValue.Array(Player.getTypeScriptAlgebraicType())},
        { name: "votes", algebraicType: __AlgebraicTypeValue.Array(Vote.getTypeScriptAlgebraicType())},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: GameState): void {
    __AlgebraicTypeValue.serializeValue(writer, GameState.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): GameState {
    return __AlgebraicTypeValue.deserializeValue(reader, GameState.getTypeScriptAlgebraicType());
  },

}

export default GameState;


